### ISSUE TITLE
[Refactor] Let's find!

### ISSUE THREAD

**Issue by kdh9949** [swsnu/swpp2019-team11#18]
I found one in TopBar.

https://github.com/swsnu/swpp2019-team11/blob/808c6ef7e907e5016fa24a74a51ccc42e2de5df8/frontend/src/components/TopBar/TopBar.js#L6-L20

I think each code line is too long.
maybe should use more indentation.

**Comment by jangsus1** [comment]
https://github.com/swsnu/swpp2019-team11/blob/0f2f2556a70f020c48c5dc857ff3b000cfa202e9/frontend/src/components/ProfileButton/ProfileButton.js#L15-L26

indentation needs to be done neatly
