### ISSUE TITLE
[Frontend] Things to implement before the Demo

### ISSUE THREAD

**Issue by kdh9949** [swsnu/swpp2019-team11#35]
We have to implement following things before demo.

1. Search Result Page
- Refine surveyBlock (display date / author / respondant count / ...)
- Implement Cart adding feature (also needs popup for better UX)
- Filter with survey start(end) date

2. Cart Page
- Implement download selected surveys with zip file

3. Upload Page
- CSVConverter (csv -> json) gives some field empty. (title / content / question type for each item)
So, we have to ask those fields to uploader.
    * we don't need to fill author field, since the backend knows the user info
- We have to give the backend only selected items.
- We have to give warning for (possible) personal info.

4. Survey Detail Page
- Show the responses of the survey with well organized form
- Implement single file download

5. Log in check (unnecessary until demo, but has to do eventually)
- Redirect to login page if not logged in
- Redirect to main page if logged in
- Has to make backend view to only test if the user is logged in.

I will do (manual) integrated testing and bugfix in Tuesday night.

**Comment by jangsus1** [comment]
Mid Demo Not-Completed List

1. Cart Page - Download selected files with zip file (working)
2. Upload Page - We have to give warning for (possible) personal info. (Not Implemented)
3. Login Check - Redirect to login page if not logged in (working)

**Comment by kdh9949** [comment]
all done
